controller_manager:
  ros__parameters:
    update_rate: 100 

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    grip_controller:
      type: joint_trajectory_controller/JointTrajectoryController
     
    grip_action_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


arm_controller:
  ros__parameters:
    joints:
      - joint_base_art1_yaw
      - joint_art1_art2_pitch
      - joint_art2_art3_pitch
      - joint_art3_art4_roll
      - joint_art4_art5_pitch
      - joint_art5_art6_roll

    command_interfaces:
      - position
    
    state_interfaces:
      - position

    open_loop_control: false

    allow_integration_in_goal_trajectories: true
    
    allow_nonzero_velocity_at_trajectory_end: true

grip_controller:
  ros__parameters:
    joints:
      - joint_hand_finger_left
      
    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    allow_nonzero_velocity_at_trajectory_end: true
    
grip_action_controller:
  ros__parameters:
    joint: joint_hand_finger_left
    action_monitor_rate: 20.0
    goal_tolerance: 0.01
    max_effort: 100.0
    allow_stalling: false
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0
    
    
